
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Onur Rahmi Ozdemir
 */
public class adminayar extends javax.swing.JFrame {
DefaultTableModel dt;
int secilenoda=0,secilenkullanici=0,secilenbolum=0;
    /**
     * Creates new form adminayar
     */
    public adminayar() {
        initComponents();
        Object[] columns2 = {"ID","Odano"};
        jTable3.setModel(new DefaultTableModel(null,columns2));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from odalar ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable3.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("oda_no")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
           Object[] columns3 = {"ID","Kullanici","Sifre"};
        jTable4.setModel(new DefaultTableModel(null,columns3));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from kullanici ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable4.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("kullaniciadi"),result.getString("sifre")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
           Object[] columns4 = {"ID","Bolum"};
        jTable1.setModel(new DefaultTableModel(null,columns4));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from bolum ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable1.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("Bolumadi")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("AYARLAR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jTable4.setBackground(new java.awt.Color(75, 177, 245));
        jTable4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable4.setForeground(new java.awt.Color(255, 255, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] { },
            new String [] {
                "ID","Odano"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(255, 255, 255));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 260, 220));

        jLabel3.setText("Kullanici Adi:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 140, 30));

        jLabel4.setText("Sifre:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, -1, -1));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 140, 30));

        jButton3.setText("Sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 70, -1));

        jButton4.setText("Duzenle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 51, 51));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Kapat");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 160, 40));

        jLabel6.setText("Kullanici Ayarlari");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, -1, -1));

        jLabel7.setText("Bolum Ayarlari");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jLabel8.setText("Bolum Adi:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 120, 30));

        jButton5.setText("Ekle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, 30));

        jButton6.setText("Duzenle");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 160, 250));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setBackground(new java.awt.Color(75, 177, 245));
        jTable3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] { },
            new String [] {
                "ID","Odano"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 140, 410));

        jLabel2.setText("Oda No:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, 30));

        jLabel5.setText("Oda Ayarlari");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        jButton1.setText("EKLE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, 30));

        jButton2.setText("Duzenle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, 30));

        jScrollPane2.setViewportView(jPanel3);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 400, 350));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1110, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        secilenoda=Integer.parseInt(dt.getValueAt(jTable3.getSelectedRow(),0).toString());
        jTextField1.setText(dt.getValueAt(jTable3.getSelectedRow(),1).toString());
    
      

    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!jTextField1.getText().equals("")){
        try{
	Connection bag = (Connection)giris.getConnection();

	java.sql.PreparedStatement st = (java.sql.PreparedStatement) bag.prepareStatement("select *, COUNT(*) as kac from odalar where oda_no='" + jTextField1.getText() + "'");
	ResultSet result = st.executeQuery();
        
       

	if(result.next()){
		if(result.getString("kac").equals("0")){
                     st = (java.sql.PreparedStatement) bag.prepareStatement("insert into odalar (oda_no) values (?)");
                     st.setString(1, jTextField1.getText());
                      st.execute();
                    
			
		}else{
			
                        
			
                    System.out.println("Bu oda Kayitlidir");   
			  
			
		}  
                
	}
        
}
catch(Exception e){
	 System.out.println(e);
}
        }else
            System.out.println("Bos alan birakmayiniz");
        
         Object[] columns2 = {"ID","Odano"};
        jTable3.setModel(new DefaultTableModel(null,columns2));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from odalar ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable3.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("oda_no")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(secilenoda!=0 && !jTextField1.getText().equals(""))   {
        try{
	Connection bag = (Connection)giris.getConnection();

	java.sql.PreparedStatement st = (java.sql.PreparedStatement) bag.prepareStatement("CALL odaduzenle(?,?)");
      
        st.setString(2,jTextField1.getText());
        st.setInt(1,secilenoda);

	 st.executeUpdate();
         System.out.println("Oda Duzeltildi");	
                    
                     
			
		               
	
}
catch(Exception e){
	 System.out.println(e);

     
    
    }
        }
        else
            System.out.println("Oda Seciniz Veya Bos Alan birakmayiniza");
        
        Object[] columns2 = {"ID","Odano"};
        jTable3.setModel(new DefaultTableModel(null,columns2));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from odalar ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable3.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("oda_no")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
       secilenkullanici=Integer.parseInt(dt.getValueAt(jTable4.getSelectedRow(),0).toString());
        jTextField2.setText(dt.getValueAt(jTable4.getSelectedRow(),1).toString());
        jTextField3.setText(dt.getValueAt(jTable4.getSelectedRow(),2).toString());
    }//GEN-LAST:event_jTable4MouseClicked

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if(secilenkullanici!=0 )   {
        try{
	Connection bag = (Connection)giris.getConnection();

	java.sql.PreparedStatement st = (java.sql.PreparedStatement) bag.prepareStatement("CALL kullanicisil(?)");
      
      
         st.setInt(1,secilenkullanici);

	 st.executeUpdate();
         System.out.println("Kullanici silindi");	
                    
                     
			
		               
	
}
catch(Exception e){
	 System.out.println(e);

     
    
    } 
    }//GEN-LAST:event_jButton3ActionPerformed
    Object[] columns3 = {"ID","Kullanici","Sifre"};
        jTable4.setModel(new DefaultTableModel(null,columns3));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from kullanici ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable4.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("kullaniciadi"),result.getString("sifre")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(secilenkullanici!=0 && !jTextField2.getText().equals("")&& !jTextField3.getText().equals(""))   {
        try{
	Connection bag = (Connection)giris.getConnection();

	java.sql.PreparedStatement st = (java.sql.PreparedStatement) bag.prepareStatement("UPDATE kullanici set  kullaniciadi=?,sifre=? where id=?");
      
        st.setString(1,jTextField2.getText());
         st.setString(2,jTextField3.getText());
         st.setInt(3,secilenkullanici);

	 st.executeUpdate();
         System.out.println("Kullanici duzeltildi");	
                    
                     
			
		               
	
}
catch(Exception e){
	 System.out.println(e);

     
    
    }
    }//GEN-LAST:event_jButton4ActionPerformed
    Object[] columns3 = {"ID","Kullanici","Sifre"};
        jTable4.setModel(new DefaultTableModel(null,columns3));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from kullanici ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable4.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("kullaniciadi"),result.getString("sifre")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
    
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       secilenbolum=Integer.parseInt(dt.getValueAt(jTable1.getSelectedRow(),0).toString());
        jTextField4.setText(dt.getValueAt(jTable1.getSelectedRow(),1).toString());
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(secilenbolum!=0 && !jTextField4.getText().equals(""))   {
        try{
	Connection bag = (Connection)giris.getConnection();

	java.sql.PreparedStatement st = (java.sql.PreparedStatement) bag.prepareStatement("UPDATE bolum set  bolumadi=? where id=?");
      
        st.setString(1,jTextField4.getText());
        
         st.setInt(2,secilenbolum);

	 st.executeUpdate();
         System.out.println("Bolum duzeltildi");	
                    
                     
			
		               
	
}
catch(Exception e){
	 System.out.println(e);

     
    
    }
    }//GEN-LAST:event_jButton6ActionPerformed
Object[] columns4 = {"ID","Bolum"};
        jTable1.setModel(new DefaultTableModel(null,columns4));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from bolum ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable1.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("Bolumadi")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         if(!jTextField4.getText().equals("")){
        try{
	Connection bag = (Connection)giris.getConnection();

	java.sql.PreparedStatement st = (java.sql.PreparedStatement) bag.prepareStatement("select *, COUNT(*) as kac from bolum where bolumadi='" + jTextField4.getText() + "'");
	ResultSet result = st.executeQuery();
        
       

	if(result.next()){
		if(result.getString("kac").equals("0")){
                     st = (java.sql.PreparedStatement) bag.prepareStatement("insert into bolum (bolumadi) values (?)");
                     st.setString(1, jTextField4.getText());
                      st.execute();
                    
			
		}else{
			
                        
			
                    System.out.println("Bu bolum Kayitlidir");   
			  
			
		}  
                
	}
        
}
catch(Exception e){
	 System.out.println(e);
}
    }//GEN-LAST:event_jButton5ActionPerformed
     Object[] columns4 = {"ID","Bolum"};
        jTable1.setModel(new DefaultTableModel(null,columns4));
        
          try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select * from bolum ");
	
        ResultSet result = st.executeQuery();
      
        while(result.next()){
            dt= (DefaultTableModel) jTable1.getModel();
            dt.addRow(new Object[]{result.getString("id"),result.getString("Bolumadi")});
        }
        
        }
        catch(Exception e){
	 System.out.println(e);
}
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminayar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
