
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.table.DefaultTableModel;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Onur Rahmi Ozdemir
 */
public class doktor extends javax.swing.JFrame {
DefaultTableModel dt;
LocalDate now = LocalDate.now();
public  static  int secilenhasta=0,secilenranduvu=0;

    /**
     * Creates new form doktor
     */
    public doktor() {
        initComponents();
       
        jTextField1.setText(isimgetir.isim(giris.girisyapan));
        balon.setVisible(false);
        try{
	Connection bag = (Connection)giris.getConnection();

	PreparedStatement st = (PreparedStatement) bag.prepareStatement("select *, COUNT(*) as kac from mesaj where alici_id='" + giris.girisyapan + "' and durum=0");
	ResultSet result = st.executeQuery();
        
       

	if(result.next()){
		if(!result.getString("kac").equals("0")){
                    
                    
			balon.setVisible(true);
		}else{
			
                        
			
                     System.out.println("yok");
			  
			
		}                
	}
}
catch(Exception e){
	 System.out.println(e);
}
        
         Object[] columns = {"Randevu no","hasta no","hasta","tarih","saat"};
        jTable1.setModel(new DefaultTableModel(null,columns));
         try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	com.mysql.jdbc.PreparedStatement st = (com.mysql.jdbc.PreparedStatement) bag.prepareStatement("select r.id,h.id,h.isim,r.randevu_tarih,s.saat_char from randevu as r ,saat as s, hastalar as h, personel as p where r.saat_id=s.id and r.doktor_id=p.id and r.hasta_id=h.id and p.id=? and r.randevu_tarih=?");
	st.setInt(1, giris.girisyapan);
        st.setString(2, now.toString());
        ResultSet result = st.executeQuery();
        while(result.next()){
            dt = (DefaultTableModel) jTable1.getModel();
            dt.addRow(new Object[]{result.getString("r.id"),result.getString("h.id"),result.getString("h.isim"),result.getString("r.randevu_tarih"),result.getString("s.saat_char")});
        }
        //"select *from kullanici where yetki='2'"
        }
        catch(Exception e){
	 System.out.println(e);
}
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        balon = new javax.swing.JLabel();
        mesaj = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Button1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(120, 229, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        balon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Onur Rahmi Ozdemir\\Downloads\\filled-circle.png")); // NOI18N
        jPanel1.add(balon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        mesaj.setIcon(new javax.swing.ImageIcon("C:\\Users\\Onur Rahmi Ozdemir\\Downloads\\message-closed-envelope.png")); // NOI18N
        mesaj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mesaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesajMouseClicked(evt);
            }
        });
        jPanel1.add(mesaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jPanel3.setBackground(new java.awt.Color(237, 69, 46));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CIKIS");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel5)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Onur Rahmi Ozdemir\\Downloads\\arrow (1).png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("DOKTOR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hastane/otomasyonu/resimler/doctor (3).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 90, 100));

        jTextField1.setBackground(new java.awt.Color(120, 229, 250));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("AD SOYAD");
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 530, 380));

        button2.setBackground(new java.awt.Color(231, 25, 53));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button2MouseExited(evt);
            }
        });
        button2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Randevu İptal");
        button2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 20));

        jPanel2.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 140, 40));

        Button1.setBackground(new java.awt.Color(4, 194, 177));
        Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1MouseExited(evt);
            }
        });
        Button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Muayene Et");
        Button1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jPanel2.add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 140, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 550, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        giris g=new giris();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void Button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseEntered
        Button1.setBackground(new Color(142, 230, 222  ));
    }//GEN-LAST:event_Button1MouseEntered

    private void Button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseExited
        
        Button1.setBackground(new Color(4,194,177  ));
    }//GEN-LAST:event_Button1MouseExited

    private void button2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseEntered
        
         button2.setBackground(new Color(234, 66, 89  ));
    }//GEN-LAST:event_button2MouseEntered

    private void button2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseExited
        button2.setBackground(new Color(231,25,53  ));
    }//GEN-LAST:event_button2MouseExited

    private void Button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button1MouseClicked
        if(secilenhasta!=0&&secilenranduvu!=0){
        muayeneet m=new muayeneet();
        m.setVisible(true);
        }else{
            System.out.println("Bir Randevu seçin");
        }
    }//GEN-LAST:event_Button1MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        secilenranduvu=Integer.parseInt(dt.getValueAt(jTable1.getSelectedRow(),0).toString());
        secilenhasta=Integer.parseInt(dt.getValueAt(jTable1.getSelectedRow(),1).toString());
      
    }//GEN-LAST:event_jTable1MouseClicked

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
       if(secilenranduvu!=0){
        try{
	Connection bag = (Connection)giris.getConnection();

	java.sql.PreparedStatement st = (java.sql.PreparedStatement) bag.prepareStatement("delete from randevu where id=?");
        st.setInt(1,secilenranduvu);
        
       
        

	 st.executeUpdate();
       	
               System.out.println("Randevu Silindi");           
                     
			
		               
	
}
catch(Exception e){
	 System.out.println(e);

     
    
    }
        Object[] columns = {"Randevu no","hasta no","hasta","tarih","saat"};
        jTable1.setModel(new DefaultTableModel(null,columns));
         try{
             
              
          
	Connection bag = (Connection) giris.getConnection();

	com.mysql.jdbc.PreparedStatement st = (com.mysql.jdbc.PreparedStatement) bag.prepareStatement("select r.id,h.id,h.isim,r.randevu_tarih,s.saat_char from randevu as r ,saat as s, hastalar as h, personel as p where r.saat_id=s.id and r.doktor_id=p.id and r.hasta_id=h.id and p.id=? and r.randevu_tarih=?");
	st.setInt(1, giris.girisyapan);
        st.setString(2, now.toString());
        ResultSet result = st.executeQuery();
        while(result.next()){
            dt = (DefaultTableModel) jTable1.getModel();
            dt.addRow(new Object[]{result.getString("r.id"),result.getString("h.id"),result.getString("h.isim"),result.getString("r.randevu_tarih"),result.getString("s.saat_char")});
        }
        //"select *from kullanici where yetki='2'"
        }
        catch(Exception e){
	 System.out.println(e);
}
       }else{
           System.out.println("Bir randevu secin");
       }
       
    }//GEN-LAST:event_button2MouseClicked

    private void mesajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesajMouseClicked
       mesaj m=new mesaj();
       m.setVisible(true);
    }//GEN-LAST:event_mesajMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doktor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doktor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button1;
    private javax.swing.JLabel balon;
    private javax.swing.JPanel button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mesaj;
    // End of variables declaration//GEN-END:variables
}
